name: Secret scan (gitleaks)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run gitleaks action
        uses: zricethezav/gitleaks-action@v1
        with:
          args: --redact --config .gitleaks.toml --baseline .gitleaks.baseline.json
      - name: Upload gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: ./gitleaks-report.json
